<?php

namespace Nutgram\Laravel\Facades;

use DateInterval;
use Illuminate\Support\Facades\Facade;
use SergiX44\Nutgram\Configuration;
use SergiX44\Nutgram\Handlers\Handler;
use SergiX44\Nutgram\Handlers\HandlerGroup;
use SergiX44\Nutgram\Handlers\Type\Command;
use SergiX44\Nutgram\Nutgram;
use SergiX44\Nutgram\Support\BulkMessenger;
use SergiX44\Nutgram\Telegram\Properties\ParseMode;
use SergiX44\Nutgram\Telegram\Properties\StickerFormat;
use SergiX44\Nutgram\Telegram\Properties\UpdateType;
use SergiX44\Nutgram\Telegram\Types\Chat\Chat;
use SergiX44\Nutgram\Telegram\Types\Chat\ChatAdministratorRights;
use SergiX44\Nutgram\Telegram\Types\Chat\ChatInviteLink;
use SergiX44\Nutgram\Telegram\Types\Chat\ChatJoinRequest;
use SergiX44\Nutgram\Telegram\Types\Chat\ChatMember;
use SergiX44\Nutgram\Telegram\Types\Chat\ChatMemberUpdated;
use SergiX44\Nutgram\Telegram\Types\Chat\ChatPermissions;
use SergiX44\Nutgram\Telegram\Types\Command\BotCommandScope;
use SergiX44\Nutgram\Telegram\Types\Command\MenuButton;
use SergiX44\Nutgram\Telegram\Types\Common\Update;
use SergiX44\Nutgram\Telegram\Types\Common\WebhookInfo;
use SergiX44\Nutgram\Telegram\Types\Description\BotDescription;
use SergiX44\Nutgram\Telegram\Types\Description\BotName;
use SergiX44\Nutgram\Telegram\Types\Description\BotShortDescription;
use SergiX44\Nutgram\Telegram\Types\Forum\ForumTopic;
use SergiX44\Nutgram\Telegram\Types\Inline\CallbackQuery;
use SergiX44\Nutgram\Telegram\Types\Inline\ChosenInlineResult;
use SergiX44\Nutgram\Telegram\Types\Inline\InlineQuery;
use SergiX44\Nutgram\Telegram\Types\Inline\InlineQueryResult;
use SergiX44\Nutgram\Telegram\Types\Inline\InlineQueryResultsButton;
use SergiX44\Nutgram\Telegram\Types\Input\InputMedia;
use SergiX44\Nutgram\Telegram\Types\Input\InputSticker;
use SergiX44\Nutgram\Telegram\Types\Internal\InputFile;
use SergiX44\Nutgram\Telegram\Types\Keyboard\ForceReply;
use SergiX44\Nutgram\Telegram\Types\Keyboard\InlineKeyboardMarkup;
use SergiX44\Nutgram\Telegram\Types\Keyboard\ReplyKeyboardMarkup;
use SergiX44\Nutgram\Telegram\Types\Keyboard\ReplyKeyboardRemove;
use SergiX44\Nutgram\Telegram\Types\Media\File;
use SergiX44\Nutgram\Telegram\Types\Message\Message;
use SergiX44\Nutgram\Telegram\Types\Message\MessageId;
use SergiX44\Nutgram\Telegram\Types\Payment\PreCheckoutQuery;
use SergiX44\Nutgram\Telegram\Types\Payment\ShippingQuery;
use SergiX44\Nutgram\Telegram\Types\Poll\Poll;
use SergiX44\Nutgram\Telegram\Types\Poll\PollAnswer;
use SergiX44\Nutgram\Telegram\Types\Sticker\MaskPosition;
use SergiX44\Nutgram\Telegram\Types\Sticker\StickerSet;
use SergiX44\Nutgram\Telegram\Types\User\User;
use SergiX44\Nutgram\Telegram\Types\User\UserProfilePhotos;
use SergiX44\Nutgram\Telegram\Types\WebApp\SentWebAppMessage;
use SergiX44\Nutgram\Testing\FakeNutgram;

/**
 * @method static int getBotId()
 * @method static void setRunningMode(string|mixed $classOrInstance)
 * @method static void run()
 * @method static void processUpdate(\SergiX44\Nutgram\Telegram\Types\Common\Update $update)
 * @method static \SergiX44\Nutgram\Nutgram stepConversation(\SergiX44\Nutgram\Conversations\Conversation|callable $callable, int|null $userId = null, int|null $chatId = null, int|null $threadId = null)
 * @method static \SergiX44\Nutgram\Nutgram endConversation(int|null $userId = null, int|null $chatId = null, int|null $threadId = null)
 * @method static \SergiX44\Container\Container getContainer()
 * @method static \SergiX44\Container\Definition bindParameter(string $name, callable $resolver)
 * @method static \SergiX44\Nutgram\Configuration getConfig()
 * @method static string getRunningMode()
 * @method static void registerMyCommands()
 * @method static \SergiX44\Nutgram\Support\BulkMessenger getBulkMessenger()
 * @method static mixed invoke(callable|array|string $callable, array $params = [])
 * @method static \SergiX44\Nutgram\Nutgram withProgress(callable|object|array|string $callable)
 * @method static mixed sendRequest(string $endpoint, array $parameters = [], array $options = [])
 * @method static bool|null downloadFile(mixed $file, string $path, array $clientOpt = [])
 * @method static string|null downloadUrl(mixed $file)
 * @method static mixed|null getMe()
 * @method static bool|null logOut()
 * @method static bool|null close()
 * @method static mixed|null sendMessage(string $text, int|string|null $chat_id = null, int|null $message_thread_id = null, mixed|string|null $parse_mode = null, mixed[]|null $entities = null, bool|null $disable_web_page_preview = null, mixed|null $link_preview_options = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null)
 * @method static mixed|null forwardMessage(int|string $chat_id, int|string $from_chat_id, int $message_id, int|null $message_thread_id = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $video_start_timestamp = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, string|null $message_effect_id = null)
 * @method static mixed[]|null forwardMessages(int|string $chat_id, int|string $from_chat_id, array $message_ids, int|null $message_thread_id = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $direct_messages_topic_id = null)
 * @method static mixed|null copyMessage(int|string $chat_id, int|string $from_chat_id, int $message_id, int|null $message_thread_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, bool|null $show_caption_above_media = null, bool|null $allow_paid_broadcast = null, int|null $video_start_timestamp = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, string|null $message_effect_id = null)
 * @method static mixed[]|null copyMessages(int|string $chat_id, int|string $from_chat_id, int|null $message_thread_id = null, array|null $message_ids = null, bool|null $disable_notification = null, bool|null $protect_content = null, bool|null $remove_caption = null, int|null $direct_messages_topic_id = null)
 * @method static mixed|null sendPhoto(mixed|string $photo, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $has_spoiler = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, bool|null $show_caption_above_media = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, array $clientOpt = [])
 * @method static mixed|null sendAudio(mixed|string $audio, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, int|null $duration = null, string|null $performer = null, string|null $title = null, mixed|string|null $thumbnail = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, array $clientOpt = [])
 * @method static mixed|null sendDocument(mixed|string $document, int|string|null $chat_id = null, int|null $message_thread_id = null, mixed|string|null $thumbnail = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $disable_content_type_detection = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, array $clientOpt = [])
 * @method static mixed|null sendVideo(mixed|string $video, int|string|null $chat_id = null, int|null $message_thread_id = null, int|null $duration = null, int|null $width = null, int|null $height = null, mixed|string|null $thumbnail = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $has_spoiler = null, bool|null $supports_streaming = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, bool|null $show_caption_above_media = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, mixed|string|null $cover = null, int|null $start_timestamp = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, array $clientOpt = [])
 * @method static mixed|null sendAnimation(mixed|string $animation, int|string|null $chat_id = null, int|null $message_thread_id = null, int|null $duration = null, int|null $width = null, int|null $height = null, mixed|string|null $thumbnail = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $has_spoiler = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, bool|null $show_caption_above_media = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, array $clientOpt = [])
 * @method static mixed|null sendVoice(mixed|string $voice, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, int|null $duration = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, array $clientOpt = [])
 * @method static mixed|null sendVideoNote(mixed|string $video_note, int|string|null $chat_id = null, int|null $message_thread_id = null, int|null $duration = null, int|null $length = null, mixed|string|null $thumbnail = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, array $clientOpt = [])
 * @method static mixed|null sendPaidMedia(int $star_count, mixed[] $media, int|string|null $chat_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, array|null $caption_entities = null, bool|null $show_caption_above_media = null, bool|null $disable_notification = null, bool|null $protect_content = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $payload = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, int|null $message_thread_id = null, array $clientOpt = [])
 * @method static mixed[]|null sendMediaGroup(mixed[] $media, int|string|null $chat_id = null, int|null $message_thread_id = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, array $clientOpt = [])
 * @method static mixed|null sendLocation(float $latitude, float $longitude, int|string|null $chat_id = null, int|null $message_thread_id = null, float|null $horizontal_accuracy = null, int|null $live_period = null, int|null $heading = null, int|null $proximity_alert_radius = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null)
 * @method static mixed|bool|null stopMessageLiveLocation(int|string|null $chat_id = null, int|null $message_id = null, string|null $inline_message_id = null, mixed|null $reply_markup = null, string|null $business_connection_id = null)
 * @method static mixed|null sendVenue(float $latitude, float $longitude, string $title, string $address, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $foursquare_id = null, string|null $foursquare_type = null, string|null $google_place_id = null, string|null $google_place_type = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null)
 * @method static mixed|null sendContact(string $phone_number, string $first_name, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $last_name = null, string|null $vcard = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null)
 * @method static mixed|null sendPoll(string $question, mixed[]|string[] $options, int|string|null $chat_id = null, int|null $message_thread_id = null, bool|null $is_anonymous = null, mixed|string|null $type = null, bool|null $allows_multiple_answers = null, int|null $correct_option_id = null, string|null $explanation = null, mixed|string|null $explanation_parse_mode = null, mixed[]|null $explanation_entities = null, int|null $open_period = null, int|null $close_date = null, bool|null $is_closed = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, mixed|string|null $question_parse_mode = null, mixed[]|null $question_entities = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null)
 * @method static mixed|null sendChecklist(mixed $checklist, string|null $business_connection_id = null, int|null $chat_id = null, bool|null $disable_notification = null, bool|null $protect_content = null, string|null $message_effect_id = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null)
 * @method static mixed|null sendDice(int|string|null $chat_id = null, int|null $message_thread_id = null, mixed|string|null $emoji = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null)
 * @method static bool|null sendMessageDraft(int $draft_id, string $text, int|null $chat_id = null, int|null $message_thread_id = null, mixed|string|null $parse_mode = null, mixed[]|null $entities = null)
 * @method static bool|null sendChatAction(mixed|string $action, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $business_connection_id = null)
 * @method static bool|null setMessageReaction(mixed[]|null $reaction = null, bool|null $is_big = null, int|string|null $chat_id = null, int|null $message_id = null)
 * @method static mixed|null getUserProfilePhotos(int|null $user_id = null, int|null $offset = null, int|null $limit = null)
 * @method static mixed|null getUserProfileAudios(int|null $user_id = null, int|null $offset = null, int|null $limit = null)
 * @method static bool|null setUserEmojiStatus(string|null $emoji_status_custom_emoji_id = null, int|null $emoji_status_expiration_date = null, int|null $user_id = null)
 * @method static mixed|null getFile(string $file_id)
 * @method static bool|null banChatMember(int|string $chat_id, int $user_id, int|null $until_date = null, bool|null $revoke_messages = null)
 * @method static bool|null unbanChatMember(int|string $chat_id, int $user_id, bool|null $only_if_banned = null)
 * @method static bool|null restrictChatMember(int|string $chat_id, int $user_id, mixed $permissions, bool|null $use_independent_chat_permissions = null, int|null $until_date = null)
 * @method static bool|null promoteChatMember(int|string $chat_id, int $user_id, bool|null $is_anonymous = null, bool|null $can_manage_chat = null, bool|null $can_post_messages = null, bool|null $can_edit_messages = null, bool|null $can_delete_messages = null, bool|null $can_post_stories = null, bool|null $can_edit_stories = null, bool|null $can_delete_stories = null, bool|null $can_manage_video_chats = null, bool|null $can_restrict_members = null, bool|null $can_promote_members = null, bool|null $can_change_info = null, bool|null $can_invite_users = null, bool|null $can_pin_messages = null, bool|null $can_manage_topics = null, bool|null $can_manage_direct_messages = null, bool|null $can_manage_tags = null)
 * @method static bool|null setChatAdministratorCustomTitle(int|string $chat_id, int $user_id, string $custom_title)
 * @method static bool|null setChatMemberTag(string|null $tag = null, int|string|null $chat_id = null, int|null $user_id = null)
 * @method static bool|null banChatSenderChat(int|string $chat_id, int $sender_chat_id)
 * @method static bool|null unbanChatSenderChat(int|string $chat_id, int $sender_chat_id)
 * @method static bool|null setChatPermissions(int|string $chat_id, mixed $permissions, bool|null $use_independent_chat_permissions = null)
 * @method static string|null exportChatInviteLink(int|string $chat_id)
 * @method static mixed|null createChatInviteLink(int|string $chat_id, string|null $name = null, int|null $expire_date = null, int|null $member_limit = null, bool|null $creates_join_request = null)
 * @method static mixed|null editChatInviteLink(int|string $chat_id, string $invite_link, string|null $name = null, int|null $expire_date = null, int|null $member_limit = null, bool|null $creates_join_request = null)
 * @method static mixed|null createChatSubscriptionInviteLink(string|int $chat_id, int $subscription_period, int $subscription_price, string|null $name = null)
 * @method static mixed|null editChatSubscriptionInviteLink(int|string $chat_id, string $invite_link, string|null $name = null)
 * @method static mixed|null revokeChatInviteLink(int|string $chat_id, string $invite_link)
 * @method static bool|null approveChatJoinRequest(int|string $chat_id, int $user_id)
 * @method static bool|null declineChatJoinRequest(int|string $chat_id, int $user_id)
 * @method static bool|null setChatPhoto(int|string $chat_id, mixed $photo, array $clientOpt = [])
 * @method static bool|null deleteChatPhoto(int|string $chat_id)
 * @method static bool|null setChatTitle(int|string $chat_id, string $title)
 * @method static bool|null setChatDescription(int|string $chat_id, string|null $description = null)
 * @method static bool|null pinChatMessage(int|string $chat_id, int $message_id, bool|null $disable_notification = null, string|null $business_connection_id = null)
 * @method static bool|null unpinChatMessage(int|string $chat_id, int|null $message_id = null, string|null $business_connection_id = null)
 * @method static bool|null unpinAllChatMessages(int|string $chat_id)
 * @method static bool|null leaveChat(int|string $chat_id)
 * @method static mixed|null getChat(int|string $chat_id)
 * @method static mixed[]|null getChatAdministrators(int|string $chat_id)
 * @method static int|null getChatMemberCount(int|string $chat_id)
 * @method static mixed|null getChatMember(int|string $chat_id, int $user_id)
 * @method static bool|null setChatStickerSet(int|string $chat_id, string $sticker_set_name)
 * @method static bool|null deleteChatStickerSet(int|string $chat_id)
 * @method static mixed[]|null getForumTopicIconStickers()
 * @method static mixed|null createForumTopic(int|string $chat_id, string $name, mixed|int|null $icon_color = null, string|null $icon_custom_emoji_id = null)
 * @method static bool|null editForumTopic(int|string $chat_id, int $message_thread_id, string|null $name = null, string|null $icon_custom_emoji_id = null)
 * @method static bool|null closeForumTopic(int|string $chat_id, int $message_thread_id)
 * @method static bool|null reopenForumTopic(int|string $chat_id, int $message_thread_id)
 * @method static bool|null deleteForumTopic(int|string $chat_id, int $message_thread_id)
 * @method static bool|null unpinAllForumTopicMessages(int|string $chat_id, int $message_thread_id)
 * @method static bool|null editGeneralForumTopic(int|string $chat_id, string $name)
 * @method static bool|null closeGeneralForumTopic(int|string $chat_id)
 * @method static bool|null reopenGeneralForumTopic(int|string $chat_id)
 * @method static bool|null hideGeneralForumTopic(int|string $chat_id)
 * @method static bool|null unhideGeneralForumTopic(int|string $chat_id)
 * @method static bool|null answerCallbackQuery(string|null $callback_query_id = null, string|null $text = null, bool|null $show_alert = null, string|null $url = null, int|null $cache_time = null)
 * @method static mixed|null getUserChatBoosts(int|string|null $chat_id = null, int|null $user_id = null)
 * @method static mixed|null getBusinessConnection(string $business_connection_id)
 * @method static bool|null setMyCommands(mixed[] $commands, mixed|null $scope = null, string|null $language_code = null)
 * @method static bool|null deleteMyCommands(mixed|null $scope = null, string|null $language_code = null)
 * @method static mixed[]|null getMyCommands(mixed|null $scope = null, string|null $language_code = null)
 * @method static mixed|null getMyName(string|null $language_code = null)
 * @method static bool|null setMyName(string|null $name = null, string|null $language_code = null)
 * @method static bool|null setMyDescription(string|null $description = null, string|null $language_code = null)
 * @method static mixed|null getMyDescription(string|null $language_code = null)
 * @method static bool|null setMyShortDescription(string|null $short_description = null, string|null $language_code = null)
 * @method static mixed|null getMyShortDescription(string|null $language_code = null)
 * @method static bool|null setMyProfilePhoto(mixed $photo)
 * @method static bool|null removeMyProfilePhoto()
 * @method static bool|null setChatMenuButton(int|null $chat_id = null, mixed|null $menu_button = null)
 * @method static mixed|null getChatMenuButton(int|null $chat_id = null)
 * @method static bool|null setMyDefaultAdministratorRights(mixed|null $rights = null, bool|null $for_channels = null)
 * @method static mixed|null getMyDefaultAdministratorRights(bool|null $for_channels = null)
 * @method static bool|null unpinAllGeneralForumTopicMessages(int|string $chat_id)
 * @method static mixed|null getUserGifts(int|null $user_id = null, bool|null $exclude_unlimited = null, bool|null $exclude_limited_upgradable = null, bool|null $exclude_limited_non_upgradable = null, bool|null $exclude_from_blockchain = null, bool|null $exclude_unique = null, bool|null $sort_by_price = null, string|null $offset = null, int|null $limit = null)
 * @method static mixed|null getChatGifts(int|string|null $chat_id = null, bool|null $exclude_unsaved = null, bool|null $exclude_saved = null, bool|null $exclude_unlimited = null, bool|null $exclude_limited_upgradable = null, bool|null $exclude_limited_non_upgradable = null, bool|null $exclude_from_blockchain = null, bool|null $exclude_unique = null, bool|null $sort_by_price = null, string|null $offset = null, int|null $limit = null)
 * @method static mixed|null repostStory(int $from_chat_id, int $from_story_id, mixed|int $active_period, string|null $business_connection_id = null, bool|null $post_to_chat_page = null, bool|null $protect_content = null)
 * @method static mixed|bool|null editMessageText(string $text, int|string|null $chat_id = null, int|null $message_id = null, string|null $inline_message_id = null, mixed|string|null $parse_mode = null, mixed[]|null $entities = null, bool|null $disable_web_page_preview = null, mixed|null $link_preview_options = null, mixed|null $reply_markup = null, string|null $business_connection_id = null)
 * @method static mixed|bool|null editMessageCaption(int|string|null $chat_id = null, int|null $message_id = null, string|null $inline_message_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, mixed|null $reply_markup = null, bool|null $show_caption_above_media = null, string|null $business_connection_id = null)
 * @method static mixed|bool|null editMessageMedia(mixed $media, int|string|null $chat_id = null, int|null $message_id = null, string|null $inline_message_id = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, array $clientOpt = [])
 * @method static mixed|bool|null editMessageLiveLocation(float $latitude, float $longitude, int|string|null $chat_id = null, int|null $message_id = null, string|null $inline_message_id = null, float|null $horizontal_accuracy = null, int|null $heading = null, int|null $proximity_alert_radius = null, mixed|null $reply_markup = null, int|null $live_period = null, string|null $business_connection_id = null)
 * @method static mixed|null editMessageChecklist(mixed $checklist, string|null $business_connection_id = null, int|null $chat_id = null, int|null $message_id = null, mixed|null $reply_markup = null)
 * @method static mixed|bool|null editMessageReplyMarkup(int|string|null $chat_id = null, int|null $message_id = null, string|null $inline_message_id = null, mixed|null $reply_markup = null, string|null $business_connection_id = null)
 * @method static mixed|null stopPoll(int|string $chat_id, int $message_id, mixed|null $reply_markup = null, string|null $business_connection_id = null)
 * @method static bool|null approveSuggestedPost(int|null $chat_id = null, int|null $message_id = null, int|null $send_date = null)
 * @method static bool|null declineSuggestedPost(int|null $chat_id = null, int|null $message_id = null, string|null $comment = null)
 * @method static bool|null deleteMessage(int|string $chat_id, int $message_id)
 * @method static bool|null deleteMessages(int|string $chat_id, int[] $message_ids)
 * @method static bool|null giftPremiumSubscription(int $user_id, int $month_count, int $star_count, string|null $text = null, mixed|string|null $text_parse_mode = null, mixed[]|null $text_entities = null)
 * @method static bool|null readBusinessMessage(int $chat_id, int $message_id, string|null $business_connection_id = null)
 * @method static bool|null deleteBusinessMessages(array $message_ids, string|null $business_connection_id = null)
 * @method static bool|null setBusinessAccountName(string $first_name, string $last_name, string|null $business_connection_id = null)
 * @method static bool|null setBusinessAccountUsername(string|null $username = null, string|null $business_connection_id = null)
 * @method static bool|null setBusinessAccountBio(string|null $bio = null, string|null $business_connection_id = null)
 * @method static bool|null setBusinessAccountProfilePhoto(mixed $photo, bool|null $is_public = null, string|null $business_connection_id = null)
 * @method static bool|null removeBusinessAccountProfilePhoto(bool|null $is_public = null, string|null $business_connection_id = null)
 * @method static bool|null setBusinessAccountGiftSettings(bool $show_gift_button, mixed $accepted_gift_types, string|null $business_connection_id = null)
 * @method static mixed|null getBusinessAccountStarBalance(string|null $business_connection_id = null)
 * @method static bool|null transferBusinessAccountStars(int $star_count, string|null $business_connection_id = null)
 * @method static mixed|null getBusinessAccountGifts(bool|null $exclude_unsaved = null, bool|null $exclude_saved = null, bool|null $exclude_unlimited = null, bool|null $exclude_limited_upgradable = null, bool|null $exclude_limited_non_upgradable = null, bool|null $exclude_unique = null, bool|null $sort_by_price = null, bool|null $offset = null, bool|null $limit = null, string|null $business_connection_id = null, bool|null $exclude_from_blockchain = null)
 * @method static bool|null convertGiftToStars(string $owned_gift_id, string|null $business_connection_id = null)
 * @method static bool|null upgradeGift(string $owned_gift_id, bool|null $keep_original_details = null, bool|null $star_count = null, string|null $business_connection_id = null)
 * @method static bool|null transferGift(string $owned_gift_id, int $new_owner_chat_id, int|null $star_count = null, string|null $business_connection_id = null)
 * @method static mixed|null postStory(mixed $content, int $active_period, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, mixed[]|null $areas = null, bool|null $post_to_chat_page = null, bool|null $protect_content = null, string|null $business_connection_id = null)
 * @method static mixed|null editStory(int $story_id, mixed $content, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, mixed[]|null $areas = null, string|null $business_connection_id = null)
 * @method static bool|null deleteStory(int $story_id, string|null $business_connection_id = null)
 * @method static mixed|null sendSticker(mixed|string $sticker, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $emoji = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null, array $clientOpt = [])
 * @method static mixed|null getStickerSet(string $name)
 * @method static mixed|null uploadStickerFile(mixed|string $sticker, mixed|string $sticker_format, int|null $user_id = null, array $clientOpt = [])
 * @method static bool|null createNewStickerSet(string $name, string $title, mixed[] $stickers, mixed|string|null $sticker_format = null, int|null $user_id = null, mixed|string|null $sticker_type = null, bool|null $needs_repainting = null, array $clientOpt = [])
 * @method static bool|null addStickerToSet(string $name, mixed $sticker, int|null $user_id = null, array $clientOpt = [])
 * @method static bool|null setStickerPositionInSet(string $sticker, int $position)
 * @method static bool|null setCustomEmojiStickerSetThumbnail(string $name, string|null $custom_emoji_id = null)
 * @method static bool|null deleteStickerFromSet(string $sticker)
 * @method static bool|null replaceStickerInSet(string $name, string $old_sticker, mixed $sticker, int|null $user_id = null, array $clientOpt = [])
 * @method static bool|null setStickerEmojiList(string $sticker, string[] $emoji_list)
 * @method static bool|null setStickerKeywords(string $sticker, string[]|null $keywords = null)
 * @method static bool|null setStickerMaskPosition(string $sticker, mixed|null $mask_position = null)
 * @method static bool|null setStickerSetThumbnail(string $name, mixed|string $format = 'static', int|null $user_id = null, mixed|string|null $thumbnail = null, array $clientOpt = [])
 * @method static mixed[]|null getCustomEmojiStickers(string[] $custom_emoji_ids)
 * @method static bool|null setStickerSetTitle(string $name, string $title)
 * @method static bool|null deleteStickerSet(string $name)
 * @method static mixed|null getAvailableGifts()
 * @method static bool|null sendGift(string $gift_id, int|null $user_id = null, string|null $text = null, string|null $text_parse_mode = null, array|null $text_entities = null, bool|null $pay_for_upgrade = null, int|string|null $chat_id = null)
 * @method static bool|null verifyUser(int $user_id, string|null $custom_description = null)
 * @method static bool|null verifyChat(int|string $chat_id, string|null $custom_description = null)
 * @method static bool|null removeUserVerification(int $user_id)
 * @method static bool|null removeChatVerification(int|string $chat_id)
 * @method static bool|null answerInlineQuery(mixed[] $results, string|null $inline_query_id = null, int|null $cache_time = null, bool|null $is_personal = null, string|null $next_offset = null, mixed|null $button = null)
 * @method static mixed|null answerWebAppQuery(string $web_app_query_id, mixed $result)
 * @method static mixed|null savePreparedInlineMessage(mixed $result, int|null $user_id = null, bool|null $allow_user_chats = null, bool|null $allow_bot_chats = null, bool|null $allow_group_chats = null, bool|null $allow_channel_chats = null)
 * @method static mixed|null sendInvoice(string $title, string $description, string $payload, string $provider_token, string $currency, mixed[] $prices, int|string|null $chat_id = null, int|null $message_thread_id = null, int|null $max_tip_amount = null, int[]|null $suggested_tip_amounts = null, string|null $start_parameter = null, string|null $provider_data = null, string|null $photo_url = null, int|null $photo_size = null, int|null $photo_width = null, int|null $photo_height = null, bool|null $need_name = null, bool|null $need_phone_number = null, bool|null $need_email = null, bool|null $need_shipping_address = null, bool|null $send_phone_number_to_provider = null, bool|null $send_email_to_provider = null, bool|null $is_flexible = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null, int|null $direct_messages_topic_id = null, mixed|null $suggested_post_parameters = null)
 * @method static string|null createInvoiceLink(string $title, string $description, string $payload, string $provider_token, string $currency, mixed[] $prices, int|null $max_tip_amount = null, int[]|null $suggested_tip_amounts = null, string|null $provider_data = null, string|null $photo_url = null, int|null $photo_size = null, int|null $photo_width = null, int|null $photo_height = null, bool|null $need_name = null, bool|null $need_phone_number = null, bool|null $need_email = null, bool|null $need_shipping_address = null, bool|null $send_phone_number_to_provider = null, bool|null $send_email_to_provider = null, bool|null $is_flexible = null, int|null $subscription_period = null, string|null $business_connection_id = null)
 * @method static bool|null answerShippingQuery(bool $ok, string|null $shipping_query_id = null, mixed[]|null $shipping_options = null, string|null $error_message = null)
 * @method static bool|null answerPreCheckoutQuery(bool $ok, string|null $pre_checkout_query_id = null, string|null $error_message = null)
 * @method static mixed|null getMyStarBalance()
 * @method static mixed|null getStarTransactions(int|null $offset = null, int|null $limit = null)
 * @method static bool|null editUserStarSubscription(string $telegram_payment_charge_id, bool $is_canceled, int|null $user_id = null)
 * @method static bool|null refundStarPayment(string $telegram_payment_charge_id, int|null $user_id = null)
 * @method static bool|null setPassportDataErrors(int $user_id, mixed[] $errors)
 * @method static mixed|null sendGame(string $game_short_name, int|null $chat_id = null, int|null $message_thread_id = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_parameters = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, bool|null $allow_paid_broadcast = null)
 * @method static mixed|bool|null setGameScore(int $score, int|null $user_id = null, bool|null $force = null, bool|null $disable_edit_message = null, int|null $chat_id = null, int|null $message_id = null, string|null $inline_message_id = null)
 * @method static mixed[]|null getGameHighScores(int|null $user_id = null, int|null $chat_id = null, int|null $message_id = null, string|null $inline_message_id = null)
 * @method static mixed[]|null sendChunkedMessage(string $text, int|string|null $chat_id = null, int|null $message_thread_id = null, mixed|string|null $parse_mode = null, mixed[]|null $entities = null, bool|null $disable_web_page_preview = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null)
 * @method static mixed[]|null sendChunkedPhoto(mixed|string $photo, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $has_spoiler = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, array $clientOpt = [])
 * @method static mixed[]|null sendChunkedAudio(mixed|string $audio, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, int|null $duration = null, string|null $performer = null, string|null $title = null, mixed|string|null $thumbnail = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, array $clientOpt = [])
 * @method static mixed[]|null sendChunkedDocument(mixed|string $document, int|string|null $chat_id = null, int|null $message_thread_id = null, mixed|string|null $thumbnail = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $disable_content_type_detection = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, array $clientOpt = [])
 * @method static mixed[]|null sendChunkedVideo(mixed|string $video, int|string|null $chat_id = null, int|null $message_thread_id = null, int|null $duration = null, int|null $width = null, int|null $height = null, mixed|string|null $thumbnail = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $has_spoiler = null, bool|null $supports_streaming = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, array $clientOpt = [])
 * @method static mixed[]|null sendChunkedAnimation(mixed|string $animation, int|string|null $chat_id = null, int|null $message_thread_id = null, int|null $duration = null, int|null $width = null, int|null $height = null, mixed|string|null $thumbnail = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, bool|null $has_spoiler = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, array $clientOpt = [])
 * @method static mixed[]|null sendChunkedVoice(mixed|string $voice, int|string|null $chat_id = null, int|null $message_thread_id = null, string|null $caption = null, mixed|string|null $parse_mode = null, mixed[]|null $caption_entities = null, int|null $duration = null, bool|null $disable_notification = null, bool|null $protect_content = null, int|null $reply_to_message_id = null, bool|null $allow_sending_without_reply = null, mixed|null $reply_markup = null, string|null $business_connection_id = null, string|null $message_effect_id = null, array $clientOpt = [])
 * @method static void macro(string $name, object|callable $macro)
 * @method static void mixin(object $mixin, bool $replace = true)
 * @method static bool hasMacro(string $name)
 * @method static void flushMacros()
 * @method static array|null getUpdates(int|null $offset = null, int|null $limit = null, int|null $timeout = null, string[]|null $allowed_updates = null)
 * @method static bool|null setWebhook(string $url, mixed|null $certificate = null, string|null $ip_address = null, int|null $max_connections = null, string[]|null $allowed_updates = ['message','edited_message','channel_post','edited_channel_post','business_connection','business_message','edited_business_message','deleted_business_messages','message_reaction','message_reaction_count','inline_query','chosen_inline_result','callback_query','shipping_query','pre_checkout_query','purchased_paid_media','poll','poll_answer','my_chat_member','chat_member','chat_join_request','chat_boost','removed_chat_boost'], bool|null $drop_pending_updates = null, string|null $secret_token = null)
 * @method static bool|null deleteWebhook(bool $drop_pending_updates = null)
 * @method static mixed|null getWebhookInfo()
 * @method static \SergiX44\Nutgram\Nutgram asResponse()
 * @method static mixed get(mixed $key, mixed $default = null)
 * @method static mixed set(mixed $key, mixed $value)
 * @method static void delete(mixed $key)
 * @method static void clear()
 * @method static mixed getGlobalData(string $key, mixed $default = null)
 * @method static bool setGlobalData(string $key, mixed $value, \DateInterval|int|null $ttl = null)
 * @method static bool deleteGlobalData(string $key)
 * @method static mixed getUserData(string $key, int|null $userId = null, mixed $default = null)
 * @method static bool setUserData(string $key, mixed $value, int|null $userId = null, \DateInterval|int|null $ttl = null)
 * @method static bool deleteUserData(string $key, int|null $userId = null)
 * @method static mixed|null currentHandler()
 * @method static array currentParameters()
 * @method static mixed validateWebAppData(string $queryString)
 * @method static mixed validateWebAppDataForThirdParty(int $botId, string $queryString, string $publicKey = 'e7bf03a2fa4602af4580703d88dda5bb59f32ed8b02a56c187fe7d34caed242d')
 * @method static mixed validateLoginData(string $queryString)
 * @method static callable|\SergiX44\Nutgram\Conversations\Conversation|\Closure|null currentConversation(int|null $userId, int|null $chatId, int|null $threadId)
 * @method static int|null userId()
 * @method static int|null chatId()
 * @method static int|null updateId()
 * @method static int|null messageId()
 * @method static int|null messageThreadId()
 * @method static string|null businessConnectionId()
 * @method static string|null inlineMessageId()
 * @method static int|null directMessagesTopicId()
 * @method static \SergiX44\Nutgram\Telegram\Types\Common\Update|null update()
 * @method static \SergiX44\Nutgram\Telegram\Types\User\User|null user()
 * @method static \SergiX44\Nutgram\Telegram\Types\Chat\Chat|null chat()
 * @method static bool isCommand()
 * @method static bool isInlineQuery()
 * @method static bool isCallbackQuery()
 * @method static bool isPreCheckoutQuery()
 * @method static bool isMyChatMember()
 * @method static bool isDirectMessagesTopic()
 * @method static bool isSuggestedPost()
 * @method static \SergiX44\Nutgram\Telegram\Types\Message\Message|null message()
 * @method static \SergiX44\Nutgram\Telegram\Types\Reaction\MessageReactionUpdated|null messageReaction()
 * @method static \SergiX44\Nutgram\Telegram\Types\Reaction\MessageReactionCountUpdated|null messageReactionCount()
 * @method static \SergiX44\Nutgram\Telegram\Types\Business\BusinessConnection|null businessConnection()
 * @method static \SergiX44\Nutgram\Telegram\Types\Business\BusinessMessagesDeleted|null deletedBusinessMessages()
 * @method static \SergiX44\Nutgram\Telegram\Types\Inline\InlineQuery|null inlineQuery()
 * @method static \SergiX44\Nutgram\Telegram\Types\Inline\ChosenInlineResult|null chosenInlineResult()
 * @method static \SergiX44\Nutgram\Telegram\Types\Inline\CallbackQuery|null callbackQuery()
 * @method static \SergiX44\Nutgram\Telegram\Types\Payment\ShippingQuery|null shippingQuery()
 * @method static \SergiX44\Nutgram\Telegram\Types\Payment\PreCheckoutQuery|null preCheckoutQuery()
 * @method static \SergiX44\Nutgram\Telegram\Types\Payment\PaidMediaPurchased|null purchasedPaidMedia()
 * @method static \SergiX44\Nutgram\Telegram\Types\Poll\Poll|null poll()
 * @method static \SergiX44\Nutgram\Telegram\Types\Poll\PollAnswer|null pollAnswer()
 * @method static \SergiX44\Nutgram\Telegram\Types\Chat\ChatMemberUpdated|null chatMember()
 * @method static \SergiX44\Nutgram\Telegram\Types\Chat\ChatJoinRequest|null chatJoinRequest()
 * @method static \SergiX44\Nutgram\Telegram\Types\Boost\ChatBoostUpdated|null chatBoost()
 * @method static \SergiX44\Nutgram\Telegram\Types\Boost\ChatBoostRemoved|null removedChatBoost()
 * @method static \SergiX44\Nutgram\Telegram\Types\Checklist\Checklist|null checklist()
 * @method static void middleware(callable|mixed|array $callable)
 * @method static void middlewares(mixed $callable)
 * @method static \SergiX44\Nutgram\Handlers\HandlerGroup group(callable $closure)
 * @method static void clearErrorHandlers(bool $exception = true, bool $apiError = true)
 * @method static \SergiX44\Nutgram\Handlers\Handler onUpdate(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onMessage(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onMessageType(mixed $type, callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onEditedMessage(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChannelPost(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onEditedChannelPost(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onBusinessConnection(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onBusinessMessage(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onEditedBusinessMessage(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onDeletedBusinessMessages(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onMessageReaction(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onMessageReactionCount(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onInlineQuery(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onInlineQueryText(string $pattern, callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChosenInlineResult(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChosenInlineResultQuery(string $pattern, callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChosenInlineResultId(string $pattern, callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onCallbackQuery(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onCallbackQueryData(string $pattern, callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onShippingQuery(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onPreCheckoutQuery(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onPreCheckoutQueryPayload(string $pattern, callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onPaidMediaPurchased(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onPaidMediaPurchasedPayload(string $pattern, callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onUpdatePoll(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onPollAnswer(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onMyChatMember(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChatMember(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChatJoinRequest(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChatBoost(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onRemovedChatBoost(callable|mixed|array $callable)
 * @method static mixed onCommand(string $command, void $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static mixed registerCommand(string|mixed $command, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onText(string $pattern, void $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onAnimation(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onAudio(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onDocument(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onPhoto(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onSticker(void $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onVideo(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onVideoNote(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onVoice(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onContact(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onDice(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onGame(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onMessagePoll(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onVenue(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onLocation(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onStory(callable|mixed|array $callable, mixed $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onNewChatMembers(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onLeftChatMember(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onChatOwnerLeft(callable|mixed|array $callable, mixed $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onChatOwnerChanged(callable|mixed|array $callable, mixed $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onNewChatTitle(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onNewChatPhoto(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onDeleteChatPhoto(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onGroupChatCreated(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onSupergroupChatCreated(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChannelChatCreated(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onMessageAutoDeleteTimerChanged(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onMigrateToChatId(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onMigrateFromChatId(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onPinnedMessage(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onInvoice(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onSuccessfulPayment(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onSuccessfulPaymentPayload(string $pattern, void $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onRefundedPayment(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onRefundedPaymentPayload(string $pattern, void $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onUsersShared(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChatShared(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onConnectedWebsite(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onPassportData(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onProximityAlertTriggered(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onBoostAdded(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onDirectMessagePriceChanged(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChecklist(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChecklistTasksDone(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onChecklistTasksAdded(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onForumTopicCreated(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onForumTopicEdited(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onForumTopicClosed(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onForumTopicReopened(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onGiveawayCreated(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onGiveaway(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onGiveawayWinners(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onGiveawayCompleted(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onVideoChatScheduled(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onVideoChatStarted(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onVideoChatEnded(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onVideoChatParticipantsInvited(callable|mixed|array $callable, \SergiX44\Nutgram\Telegram\Properties\UpdateType $target = 'message')
 * @method static \SergiX44\Nutgram\Handlers\Handler onWebAppData(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler fallback(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler fallbackOn(mixed $type, callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler onException(callable|string $callableOrException, callable|null $callable = null)
 * @method static \SergiX44\Nutgram\Handlers\Handler onApiError(callable|string $callableOrPattern, callable|null $callable = null)
 * @method static \SergiX44\Nutgram\Handlers\Handler registerApiException(string $exceptionClass)
 * @method static \SergiX44\Nutgram\Handlers\Handler beforeApiRequest(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\Handler afterApiRequest(callable|mixed|array $callable)
 * @method static \SergiX44\Nutgram\Handlers\CollectHandlers throttle(int $maxAttempts, int $decaySeconds = 60, string|null $key = null, null|callable $warningCallback = null)
 * @method static \SergiX44\Nutgram\Middleware\RateLimit|null getRateLimit()
 * @method static void appendRateLimiters(array $rateLimiters)
 * @method static \SergiX44\Nutgram\Handlers\CollectHandlers withoutThrottle(bool $value = true)
 * @method static bool isWithoutRateLimit()
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram instance(mixed $update = null, array $responses = [], \SergiX44\Nutgram\Configuration|null $config = null)
 * @method static array getRequestHistory()
 * @method static array getDumpHistory()
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram willReceive(array|int|true $result, bool $ok = true)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram willReceivePartial(array|int|true $result, bool $ok = true)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram reply()
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram clearCache()
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram willStartConversation(bool $remember = true)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram dump()
 * @method static never dd()
 * @method static array getMethodsReturnTypes()
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram withoutMiddleware(string|string[] $middleware)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram overrideMiddleware(string|string[] $middleware)
 * @method static array getActualData(\GuzzleHttp\Psr7\Request $request, array $mapping = [])
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram setCommonUser(\SergiX44\Nutgram\Telegram\Types\User\User $user)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram setCommonChat(\SergiX44\Nutgram\Telegram\Types\Chat\Chat $chat)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram hearUpdate(mixed $update)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram hearUpdateType(mixed $type, array $partialAttributes = [])
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram hearMessage(array $value)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram hearText(string $value)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram hearCallbackQueryData(string $value)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertRaw(callable $closure, int|null $index = null, string $message = '')
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertCalled(string $method, int $times = 1)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertReply(string|string[] $method, array|null $expected = null, int|null $index = null)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertReplyMessage(array $expected, int|null $index = null, string|null $forceMethod = null)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertReplyText(string $expected, int|null $index = null)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertActiveConversation(int|null $userId = null, int|null $chatId = null, int|null $threadId = null)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertNoConversation(int|null $userId = null, int|null $chatId = null, int|null $threadId = null)
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertNoReply()
 * @method static \SergiX44\Nutgram\Testing\FakeNutgram assertSequence(callable ...$callbacks)
 *
 * @see \SergiX44\Nutgram\Nutgram
 * @see \SergiX44\Nutgram\Testing\FakeNutgram
 * @see \SergiX44\Nutgram\Telegram\Client
 * @see \SergiX44\Nutgram\Proxies\UpdateProxy
 * @see \SergiX44\Nutgram\Proxies\UpdateDataProxy
 * @see \SergiX44\Nutgram\Proxies\GlobalCacheProxy
 * @see \SergiX44\Nutgram\Proxies\UserCacheProxy
 * @see \SergiX44\Nutgram\Handlers\FireHandlers
 * @see \SergiX44\Nutgram\Support\ValidatesWebData
 * @see \SergiX44\Nutgram\Support\HandleLogging
 * @see \SergiX44\Nutgram\Handlers\Listeners\UpdateListeners
 * @see \SergiX44\Nutgram\Handlers\Listeners\MessageListeners
 * @see \SergiX44\Nutgram\Handlers\Listeners\SpecialListeners
 * @see \SergiX44\Nutgram\Support\InteractsWithRateLimit
 * @see \SergiX44\Nutgram\Testing\Hears
 * @see \SergiX44\Nutgram\Testing\Asserts
 */
class Telegram extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'telegram';
    }

    public static function fake(): void
    {
        static::swap(Nutgram::fake());
    }
}
