<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Bot Instance
    |--------------------------------------------------------------------------
    |
    | This option controls the default bot instance
    | that gets used by Telegram facade.
    | This allows you to specify, which of your bots you wish to use
    | as the default instance for your app.
    |
    */

    'default' => 'bot',

    /*
    |--------------------------------------------------------------------------
    | Bot Instances
    |--------------------------------------------------------------------------
    |
    | Here you may configure the bot instances for your application.
    |
    */

    'instances' => [

        'bot' => [
            'token' => env('TELEGRAM_TOKEN'),
            'config' => [],
            'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
        ]

    ],

    /*
    |--------------------------------------------------------------------------
    | Safe Mode
    |--------------------------------------------------------------------------
    |
    | This option controls the safe mode for all your bots.
    | If enabled, the webhooks will only accept requests from Telegram servers.
    |
    */

    'safe_mode' => env('APP_ENV', 'local') === 'production',

    /*
    |--------------------------------------------------------------------------
    | Routes
    |--------------------------------------------------------------------------
    |
    | If enabled, the service provider will automatically load
    | the routes/telegram.php file.
    | You can use this file to register your bots commands and handlers.
    |
    */

    'routes' => false,

    /*
    |--------------------------------------------------------------------------
    | Nutgram Mixins
    |--------------------------------------------------------------------------
    |
    | If enabled, the service provider will automatically load
    | the built-in Nutgram mixins for Laravel.
    |
    */

    'mixins' => false,

    /*
    |--------------------------------------------------------------------------
    | Namespace
    |--------------------------------------------------------------------------
    |
    | Path to save files generated by nutgram:make commands.
    |
    */

    'namespace' => app_path('Telegram'),

];
